"""stella_vslam backend (equirectangular monocular SLAM) run in a Docker container.

The upstream library is built unmodified (docker/stella/Dockerfile). slam3d's driver
(cpp/stella_driver) is compiled against it and writes online poses, causal local observations and
the final optimised map. Scale of the result is ARBITRARY (monocular).
"""
from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import yaml

from slam3d.geometry.transforms import quat_to_R

IMAGE = "slam3d-stella:e445b54"
REPO = Path(__file__).resolve().parents[3]
DRIVER_BUILD = REPO / "cpp/stella_driver/build"
DRIVER_BIN = DRIVER_BUILD / "slam3d_stella_driver"


def make_config(width: int, height: int, fps: float, out_path: Path, overrides: dict | None = None) -> dict:
    cfg = {
        "Camera": {"name": "equirectangular 360", "setup": "monocular", "model": "equirectangular",
                   "fps": float(fps), "cols": int(width), "rows": int(height), "color_order": "BGR"},
        "Preprocessing": {"min_size": 800},
        "Feature": {"name": "ORB", "scale_factor": 1.2, "num_levels": 8,
                    "ini_fast_threshold": 20, "min_fast_threshold": 7},
        "Mapping": {"backend": "g2o", "baseline_dist_thr_ratio": 0.02, "redundant_obs_ratio_thr": 0.95,
                    "num_covisibilities_for_landmark_generation": 20,
                    "num_covisibilities_for_landmark_fusion": 20, "residual_deg_thr": 0.4},
        "Tracking": {"backend": "g2o"},
        "LoopDetector": {"backend": "g2o", "enabled": True, "reject_by_graph_distance": True,
                         "min_distance_on_graph": 50},
        "GraphOptimizer": {"min_num_shared_lms": 200},
        "GlobalOptimizer": {"thr_neighbor_keyframes": 100},
        "System": {"map_format": "msgpack", "num_grid_cols": 96, "num_grid_rows": 48},
    }
    for sec, vals in (overrides or {}).items():
        cfg.setdefault(sec, {}).update(vals)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("# generated by slam3d\n" + yaml.safe_dump(cfg, sort_keys=False))
    return cfg


def _docker(cmd: str, log_path: Path | None = None, name: str | None = None):
    uid, gid = os.getuid(), os.getgid()
    home = str(Path.home())
    args = ["docker", "run", "--rm", "--user", f"{uid}:{gid}", "-v", f"{home}:{home}", "-w", str(REPO)]
    if name:
        args += ["--name", name]
    args += [IMAGE, "bash", "-lc", cmd]
    if log_path:
        with open(log_path, "w") as lf:
            return subprocess.run(args, stdout=lf, stderr=subprocess.STDOUT)
    return subprocess.run(args)


def build_driver(log_path: Path | None = None) -> Path:
    DRIVER_BUILD.mkdir(parents=True, exist_ok=True)
    r = _docker(f"cd {DRIVER_BUILD} && cmake -DSTELLA_SRC_DIR=/stella_vslam .. && make -j8", log_path)
    if r.returncode != 0 or not DRIVER_BIN.exists():
        raise RuntimeError(f"driver build failed, see {log_path}")
    return DRIVER_BIN


def run(frames_csv: Path, out_dir: Path, config_yaml: Path, vocab: Path, mask: Path | None = None,
        obs_every: int = 3, max_frames: int | None = None, log_path: Path | None = None,
        container_name: str | None = None) -> int:
    if not DRIVER_BIN.exists():
        build_driver(out_dir / "driver_build.log")
    out_dir.mkdir(parents=True, exist_ok=True)
    cmd = (f"{DRIVER_BIN} --vocab {vocab} --config {config_yaml} --frames {frames_csv} --out {out_dir} "
           f"--obs-every {obs_every}")
    if mask:
        cmd += f" --mask {mask}"
    if max_frames:
        cmd += f" --max-frames {max_frames}"
    return _docker(cmd, log_path, name=container_name).returncode


# ------------------------------------------------------------------------------------------------
# output parsers
# ------------------------------------------------------------------------------------------------
@dataclass
class OnlinePoses:
    idx: np.ndarray
    t: np.ndarray
    state: np.ndarray  # str
    loop_ba: np.ndarray  # bool
    n_tracked: np.ndarray
    track_ms: np.ndarray
    T: np.ndarray  # (N,4,4) T_world_cam, NaN when lost
    valid: np.ndarray


def load_online_poses(path) -> OnlinePoses:
    idx, t, st, lb, nt, ms, vals = [], [], [], [], [], [], []
    with open(path) as f:
        for line in f:
            if line.startswith("#"):
                continue
            p = line.split()
            if len(p) < 13:
                continue
            idx.append(int(p[0])); t.append(float(p[1])); st.append(p[2]); lb.append(p[3] == "1")
            nt.append(int(p[4])); ms.append(float(p[5])); vals.append([float(x) for x in p[6:13]])
    v = np.asarray(vals, float).reshape(-1, 7)
    valid = np.isfinite(v).all(1)
    T = np.full((len(v), 4, 4), np.nan)
    if valid.any():
        T[valid] = np.eye(4)
        T[valid, :3, :3] = quat_to_R(v[valid, 3:7])
        T[valid, :3, 3] = v[valid, :3]
    return OnlinePoses(np.array(idx), np.array(t), np.array(st), np.array(lb), np.array(nt), np.array(ms), T, valid)


def load_local_obs(path):
    """Returns list of (frame_idx, t, landmark_ids (n,), points_cam (n,3))."""
    data = Path(path).read_bytes()
    out, off = [], 0
    rec = np.dtype([("id", "<u4"), ("p", "<f4", 3)])
    while off + 16 <= len(data):
        idx = int(np.frombuffer(data, "<i4", 1, off)[0]); off += 4
        t = float(np.frombuffer(data, "<f8", 1, off)[0]); off += 8
        n = int(np.frombuffer(data, "<i4", 1, off)[0]); off += 4
        arr = np.frombuffer(data, rec, n, off); off += n * rec.itemsize
        out.append((idx, t, arr["id"].copy(), arr["p"].astype(np.float64)))
    return out


def load_landmarks(path):
    rec = np.dtype([("id", "<u4"), ("p", "<f4", 3), ("nobs", "<u4"), ("first_kf", "<u4")])
    a = np.fromfile(path, rec)
    return {"id": a["id"], "xyz": a["p"].astype(np.float64), "nobs": a["nobs"], "first_kf": a["first_kf"]}


def load_keyframes(path):
    a = np.genfromtxt(path, delimiter=",", skip_header=1).reshape(-1, 14)
    T = np.tile(np.eye(4), (len(a), 1, 1))
    T[:, :3, :3] = a[:, 2:11].reshape(-1, 3, 3)
    T[:, :3, 3] = a[:, 11:14]
    order = np.argsort(a[:, 1])
    return {"id": a[order, 0].astype(int), "t": a[order, 1], "T": T[order]}


def load_kf_obs(path):
    rec = np.dtype([("kf", "<u4"), ("lm", "<u4"), ("uv", "<f4", 2)])
    return np.fromfile(path, rec)
